### ISSUE TITLE
Opening/Closing Refrigerator, Cupboards, etc.

### ISSUE THREAD

**Issue by DomestiqueBaston** [DomestiqueBaston/JAVA_JOLT#1]
When using the following animations:
**Get_Something_High_1**, opening appears at **frame 8**
**Get_Something_High_2**, opening appears at **frame 8**
**Get_Something_Low**, opening appears at **frame 7**
**Get_Something_Low_Mid**, opening appears at **frame 8**
**Get_Something_Lowest**, opening appears at **frame 8**
**Get_Something_Mid**, opening appears at **frame 8**

We only use opening/closing sound with cupboards and whatever looks like a cupboard, a drawer, ovens, a dishwasher. **NOT** with stuff like knifes, boxes, pots, plants , Light switches...

We are using **Get_Something_High_1** and **Get_Something_High_2** (randomly) with **upper cupboards, Microwave oven, Painting** (on the left of the kitchen) and **what's inside** (if there is).
We are using **Get_Something_Low_Mid** with **refrigerator doors, chair, upper drawers, light switches.**
We are using **Get_Something_Mid** with **what's on the kitchen worktop, water/ice fountain on the refrigerator left door**.
We are using **Get_Something_Low** with left drawer (2 and 3), oven, towels, stool
We are using **Get_Something_Lowest** with **private drawer, oven bottom and coffee beans on the ground** (not visible in the beginning of the game).

This list will be updated (of course)!

**Comment by glevner** [comment]
We will implement a mechanism which determines the animation automatically depending on the height of the thing being opened/closed.
