### ISSUE TITLE
Timing adjustments for chained animations...

### ISSUE THREAD

**Issue by DomestiqueBaston** [DomestiqueBaston/JAVA_JOLT#18]
Hej!

We need to be able to adjust how long an animation should be played (even though it's not a loop) before going to the next or to the next thing Rowena says or so. For instance at the end of the first attempt to make a coffee: The Do_Stuff animation, then what she says, then the Do_Erk_Stuff animation then what she says isn't perfectly accurate as is. Can we imagine some timers I could handle to adjust that? Or have several timers we could choose from? All that in order to spare you the code modifications every time I'd like to adjust them?

**Comment by glevner** [comment]
Hmm, just tell me exactly what you want her to do, then I'll see. FYI that's all handled by two functions in `ROWENA.gd` : `get_something()` and `do_stuff()`.

**Comment by DomestiqueBaston** [comment]
Ok. The thing is, that every animation is played 1 time then what should come next comes. Sometimes, we could use 1.5 or 2 times the animation. Eventually leave some more time before or after saying something too... I made the Comment Timeout back to 4 instead of 3 and it helped but I think that won't be the case every single time.

**Comment by DomestiqueBaston** [comment]
Maybe we can simplify this by using 1 animation cycle a unit. So if we need more or less time, we can add or remove one cycle... But maybe that doesn't necessarily simplify things... :)

**Comment by glevner** [comment]
I don't know what that means! Let me know exactly what needs to be changed.

**Comment by DomestiqueBaston** [comment]
I'd like to be able to adjust how long Rowena goes **Waiting** before **saying something** or **doing something** else but since it needs to be adjusted with very probably several attempts, I wouldn't ask you to add 3 frames, then remove 2 then add 1, etc. As is, for instance, Rowena chains every action too quickly with the next one. **^_^'**

**Comment by glevner** [comment]
Dans un premier temps je propose que tu ajoutes les pauses que tu veux dans le code. Quand tu es satisfait du résultat, je ferai ça proprement.

Dans les fonctions `get_something()` et `do_stuff()`, tu ajoutes une ligne comme celle-ci quand tu veux une pause :

    await get_tree().create_timer(0.1).timeout

Ça fait une pause de 0,1 secondes avant de procéder.

**Comment by DomestiqueBaston** [comment]
👍👍👍🙏🙏🙏
