### ISSUE TITLE
Inventory UI improvements

### ISSUE THREAD

**Issue by DomestiqueBaston** [DomestiqueBaston/JAVA_JOLT#20]
While the mouse is over an item in the inventory other than the selected one, color it blue (the doctor's text color). (The selected item is Rowena red, and other items are white.)

Also, remove the cross cursor from inventory actions; the default action is to use the item (hand).

**Comment by DomestiqueBaston** [comment]
Could we also have the mouse cursor change color when hovering things in the Inventory (red when over an object)?

**Comment by glevner** [comment]
> Could we also have the mouse cursor change color when hovering things in the Inventory (red when over an object)?

This is already done.

**Comment by DomestiqueBaston** [comment]
Oops! :)
