### ISSUE TITLE
Close comment when user clicks

### ISSUE THREAD

**Issue by DomestiqueBaston** [DomestiqueBaston/JAVA_JOLT#26]
When looking at something then Rowena says something, we can change the cursor to try to take that thing (eventually) but as long as Rowena's comment is displayed, we can't really get any result. We have to wait for the comment to disappear before doing something. Could clicking somewhere close Rowena's comment before the end of the timer in order to interact with that thing?

**Comment by glevner** [comment]
The user can now close the comment box by clicking on it. I don't think it is necessary to explicitly close it when the user clicks elsewhere, because the comment box does not inhibit interaction outside the box.

**Comment by DomestiqueBaston** [comment]
👍👍👍🙏🙏🙏😁
