### ISSUE TITLE
When Rowena plays Do_Stuff...

### ISSUE THREAD

**Issue by DomestiqueBaston** [DomestiqueBaston/JAVA_JOLT#28]
When she uses the **small towel** and the **milk** together, we **shouldn't** hear the Do_Stuff sound.
When she uses the **milked small towel** with the **filter holder**, we **shouldn't** hear the Do_Stuff sound.
When she uses the **butter knife** on the **coffee maker**, ok, we can hear the Do stuff sound!
...
As a matter of fact, we only hear that sound when she does something that could possibly be noisy.

**Comment by glevner** [comment]
See also issue #1.

**Comment by glevner** [comment]
Si tu veux que le son soit optionnel, il faut le déclencher dans le code, comme pour Open_Close. Pour Do_Stuff ça va, mais pour Do_Erk_Stuff il y a deux sons différents, décalés. Tu pourrais faire en sorte qu'il n'y en ait qu'un ?

**Comment by DomestiqueBaston** [comment]
Je pense que oui. Je fais ça.

**Comment by DomestiqueBaston** [comment]
En fait, Je crois bien que chaque fois qu'on utilise **Do_Erk_Stuff**, les sons ne gênent pas.
C'est pour **Do_Stuff** que ça peut poser problème.
