### ISSUE TITLE
Kettle, Fruit Basket, Milk Bottle(s) in the fridge, etc...

### ISSUE THREAD

**Issue by DomestiqueBaston** [DomestiqueBaston/JAVA_JOLT#29]
After Rowena takes those objects, when hovering those places, you still get a red cursor and you shouldn't (at least you can't take them again until you throw them away and, that's ok). That doesn't happen when you take the small towel and that's the right behavior.

**Comment by glevner** [comment]
For the fruit basket and the milk bottles you **should** still get a red cursor, because she only took one bottle and one apple. The kettle should behave like the towel, though, I will check.

**Comment by glevner** [comment]
Also: things taken from the fridge reappear if you close it and open it again. That is a bug.

**Comment by DomestiqueBaston** [comment]
Ok. :)
