### ISSUE TITLE
Inventory and cursor

### ISSUE THREAD

**Issue by DomestiqueBaston** [DomestiqueBaston/JAVA_JOLT#30]
When opening the Inventory, you get the Hand cursor. Maybe you should have the cross or at least the last active cursor.

**Comment by glevner** [comment]
We eliminated the cross cursor from the inventory in issue #20 at JV's request. There are only two inventory cursors: hand and trash.

**Comment by DomestiqueBaston** [comment]
Ok. I forgot about that! :) That's good, then.
