### ISSUE TITLE
Prompt for confirmation before quitting

### ISSUE THREAD

**Issue by DomestiqueBaston** [DomestiqueBaston/JAVA_JOLT#32]
Pour quitter le jeu :
Il suffira de cliquer sur la fenêtre de droite dans la cuisine (avec le curseur "Quit"). À ce moment-là, la fenêtre de dialogue s’ouvrira et affichera ce que Rowena va dire avec un choix pour le joueur « Hmm... Really? 'Cause if I mess this up… » et les choix de réponses seront « Nothing ventured, nothing gained, I'd say… » (oui) et « Actually, I'd rather stay in this misery… » (non).

Tout sera exceptionnellement en une seule fenêtre de dialogue (donc pas comme quand elle discute avec le Doc. par exemple)

On sautera une ligne entre ce que dit Rowena et ses choix de réponses.

**Comment by glevner** [comment]
Ça risque d'être un peu compliqué à mettre en place, on verra...

**Comment by DomestiqueBaston** [comment]
D'accord ! On peut trouver une solution plus simple, si tu veux. Si tant est qu'on puisse faire plus simple, bien entendu. Sinon, on laissera tomber.

**Comment by glevner** [comment]
En attendant on a déjà la possibilité de l'arrêter avant qu'elle n'arrive à la fenêtre...

**Comment by DomestiqueBaston** [comment]
Ok.
