### ISSUE TITLE
Linking Introduction animation with the game itself

### ISSUE THREAD

**Issue by DomestiqueBaston** [DomestiqueBaston/JAVA_JOLT#33]
After playing the introduction, we actually start the game with the first dialogue which means that we can't have the blinking **?** button until the end of the dialogue.

**Comment by DomestiqueBaston** [comment]
Beside, there's a short freeze when going from INTRO.tscn to JAVAJOLT.tscn. Maybe a preload of the JAVAJOLT.tscn?

This will probably also happen later when we'll go from JAVAJOLT.tscn to OUTRO.tscn. :)

**Comment by glevner** [comment]
> After playing the introduction, we actually start the game with the first dialogue which means that we can't have the blinking **?** button until the end of the dialogue.

That's done.
