### ISSUE TITLE
Fix the application icon for macOS

### ISSUE THREAD

**Issue by glevner** [DomestiqueBaston/JAVA_JOLT#36]
`JJ.icns` is not a valid icon file.

**Comment by DomestiqueBaston** [comment]
@glevner Est-ce que tu pourras essayer en remplaçant le fichier icns par le fichier JJ.png (à la racine du projet) ? Je n'ai pas de Mac et c'est difficile de trouver la solution d'autant que je ne voispas beacoup d'aide en ligne ou alors, c'est inaccessible pour un non-Mac.

**Comment by glevner** [comment]
Si tu me dis à partir de quelle image il faut le faire, je peux m’en
occuper. C’est un fichier qui contient la même image à plusieurs
résolutions différentes.

Le sam. 7 sept. 2024 à 15:13, DomestiqueBaston ***@***.***> a
écrit :

**Comment by DomestiqueBaston** [comment]
Ok. Je t'envoie les images tout à l'heure !

**Comment by glevner** [comment]
Une seule image…

Le sam. 7 sept. 2024 à 19:15, DomestiqueBaston ***@***.***> a
écrit :

> Ok. Je t'envoie les images tout à l'heure !
>

**Comment by DomestiqueBaston** [comment]
Alors jj.png. si tu dois l'agrandir, sans extrapolation (nearest) et en
multiple entiers.
