### ISSUE TITLE
A better place for the Comments Label.

### ISSUE THREAD

**Issue by DomestiqueBaston** [DomestiqueBaston/JAVA_JOLT#7]
Il serait chouette aussi d'avoir le Labels des Comments de Rowena qui se trouve, on va dire à 5 pixels d'elle quand elle est à l'arrêt et qu'elle ne fait rien. Pour le moment, il est trop loin d'elle, c'est pas très joli.

F.

**Comment by glevner** [comment]
Ce n'est pas aussi simple que ça. La boîte des commentaires se met juste à côté d'elle. Mais comme le texte est centré dans la boîte, la position réelle du texte dépend du texte... On pourrait aligner le texte différemment -- _left-justified_ quand il se trouve à droite, _right-justified_ quand il se trouve à gauche -- mais ça ne serait pas forcément plus joli.

**Comment by DomestiqueBaston** [comment]
Ok. Je vais faire des tests pour trouver une solution... Mais tu as probablement raison concernant _right-justified_, ça risque d'être au moins bizarre.

**Comment by DomestiqueBaston** [comment]
J'ai mis en ligne une version avec un background. Ça devrait aider. La taille horizontale de la boîte est fixée à minimum 65px. Je crois que ça sert aussi de maximum car quand le texte ne rentre pas, Godot va à la ligne et rallonge la boîte verticalement. On tâchera juste de trouver une bonne largeur pour tout le temps et ça ira. Avec une largeur fixe, on doit pouvoir placer le bloc de commentaire à droite ou à gauche de Rowena en restant avec un texte centré dans le bloc.

En l'état, il faut donc modifier ton code pour qu'il retrouve le Label Comments qui est à présent fils d'un PanelContainer appelé Comment_Box.

**Comment by glevner** [comment]
Il y a déjà une largeur fixe, fixée dans le code, d'un tiers de la largeur
de la fenêtre.

**Comment by DomestiqueBaston** [comment]
Ok. J'imagine que le code overide le truc dans la scène.

F.

**Comment by glevner** [comment]
Avec ce nouveau mécanisme je ne connais pas la taille du Label à l'avance. Du coup, pour centrer le commentaire en vertical, j'ai été obligé d'ajouter un CenterContainer.

**Comment by DomestiqueBaston** [comment]
Ok, je regarde(rai) !

F.
