### ISSUE TITLE
Improving interaction with the game...

### ISSUE THREAD

**Issue by DomestiqueBaston** [DomestiqueBaston/JAVA_JOLT#9]
So far some things are not very user friendly.

Here's what we should improve:

**1)** When Rowena opens the refrigerator we can't see what's inside the door but when we make her move to the side then the refrigerator close. It can't stay that way. **When we have a solution, I guess we'll apply it to every other furniture she's able to open.** The problem is that if she's moved aside and we ask her to do something not related with what's inside the refrigerator, then it closes and it will be very weird. I don't know how to solve this right now... Any idea? I don't know if we can have several doors if we decide to keep things open until closed. of any kind open at the same time in the Kitchen (because of Z index mainly). I guess we can't ask Rowena to open the cutlery drawer then have her go to close the refrigerator's door before opening the drawer as the entire game makes the player open things one after another...

**2)** About the Comment Box. We have a similar issue there: when we use the Eye cursor on something. When the cursor leaves the Collider then the Comment Box closes. Very annoying in general and in particular with very little colliders. Could we A) wait for the player to click somewhere else before closing the Comment Box? Or B) imagine to have a timer before the comment box closes? I'd rather choose the A) solution.

**3)** As is, when the refrigerator door is open, we still have access to what's behind it and it shouldn't be the case...

**-= EDIT from July 30th =-**

Great! You've improved the situation with the fridge a lot. Two points:

When we click to go somewhere else and the fridge is closed. We should make Rowena play her animation to close the fridge (the very same she plays when opening it) before leaving.

When Rowena is in front of the fridge and we ask her to open the fridge, she stays in front of what's inside it and this is bothering. Maybe we could make her go aside the Fridge collider before opening it. That still won't fix the issue when she's outside of the closed fridge and becomes in front of the door and what's inside when it's open. Je me demande si on ne pourrait pas pousser un peu plus loin le truc et permettre à Rowena, quand le frigo est ouvert de se déplacer comme ça, elle pourrait vois ce qu'il y a dedans plus facilement. En revanche toute autre action ferait qu'elle ne ferme le frigo avant de l'executer. Cela implique d'avoir accès aux autres objets de la cuisine, ceci dit. Si tu as une idée...

**Comment by glevner** [comment]
The comment box now stays open until the user moves or clicks on something.

**Comment by glevner** [comment]
While the refrigerator is open, the user can only look at stuff inside it.

**Comment by glevner** [comment]
Suggestion pour le frigo : il ne se ferme que sur demande (_ex._ en cliquant sur la porte du frigo), ou quand on ouvre autre chose. Mais s'il faut que Rowena aille jusqu'au frigo pour le refermer, ça peut prendre du temps. Alors je vois deux possibilités, si on essaie d'ouvrir autre chose alors que le frigo est ouvert : soit on ferme le frigo à distance, sans que Rowena se déplace ; soit elle va fermer le frigo avant de se déplacer à plus d'une certaine distance du frigo.

**Comment by DomestiqueBaston** [comment]
Oui, je crois qu'on va faire comme tu le suggères. La faire fermer
elle-même une porte lorsqu'elle est à l'autre bout de la pièce, ça sera
chiant. Donc, si Rowena est loin, le frigo se ferme tout seul. Consernant
la distance, disons par exemple que si elle est à plus d'1/3 de largeur
d'écran, ça se ferme tout seul ? Tu peux aussi mettre cette valeur en
export comme ça je pourrai affiner le truc.

Ferdi.

**Comment by glevner** [comment]
OK, on peut fermer la porte en cliquant dessus. La porte ne se ferme pas automatiquement quand on se déplace. Mais si on fait autre chose, la porte se ferme d'abord. (Pour l'instant la seule autre chose qu'on peut faire, c'est de sauter par la fenêtre.) Si Rowena se trouve à moins de 60 pixels de la porte, elle se déplace pour la fermer, sinon la porte se ferme toute seule. Une variable _auto_close_distance_ permet de régler cette distance.

**Comment by DomestiqueBaston** [comment]
Génial ! Du coup, je fais un saut à Brest, aujourd'hui ! 😁😁😁

Oui, oui, aucun rapport mais c'est vrai.

F.
